import {
    BooksIcon,
    ButterflyIcon,
    CoinsIcon,
    ConfettiIcon,
    CrownIcon,
    DiceThreeIcon,
    EvergreenTreeIcon,
    ExamIcon,
    FastForwardIcon,
    FireIcon,
    GiftIcon,
    GlobeIcon,
    GraduationCapIcon,
    HandPeaceIcon,
    MagicWandIcon,
    MedalIcon,
    MoonStarsIcon,
    MusicNotesIcon,
    PaletteIcon,
    PawPrintIcon,
    ShootingStarIcon,
    SnowflakeIcon,
    SparkleIcon,
    StarIcon,
    StudentIcon,
    TrophyIcon,
    UnicornIcon,
    YinYangIcon,
    type IconProps
} from 'gymcord-design-system';
import { LeagueIcon } from './api';

/** Every league icon option, keyed by the value stored on `leagues.league_icon` — shared between the CreateLeague picker and any badge that renders a league's chosen icon. */
export const LEAGUE_ICON_COMPONENTS: Record<LeagueIcon, (props: IconProps) => JSX.Element> = {
    books: BooksIcon,
    butterfly: ButterflyIcon,
    coins: CoinsIcon,
    confetti: ConfettiIcon,
    crown: CrownIcon,
    'dice-three': DiceThreeIcon,
    'evergreen-tree': EvergreenTreeIcon,
    exam: ExamIcon,
    'fast-forward': FastForwardIcon,
    fire: FireIcon,
    gift: GiftIcon,
    globe: GlobeIcon,
    'graduation-cap': GraduationCapIcon,
    'hand-peace': HandPeaceIcon,
    'magic-wand': MagicWandIcon,
    medal: MedalIcon,
    'moon-stars': MoonStarsIcon,
    'music-notes': MusicNotesIcon,
    palette: PaletteIcon,
    'paw-print': PawPrintIcon,
    'shooting-star': ShootingStarIcon,
    snowflake: SnowflakeIcon,
    sparkle: SparkleIcon,
    star: StarIcon,
    student: StudentIcon,
    trophy: TrophyIcon,
    unicorn: UnicornIcon,
    'yin-yang': YinYangIcon
};
